### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by MartinKockH** [TrevorBivi/Old-School-RuneScape-Bot-API#1]
Hi!
First of all, congratulations. Its a nice work you have made here, very clear too.

I have one questions of your work and that is:
¿Are you using python version 3.0 or 3.1? 

PD: The win32 modules are working up to version 3.1

**Comment by TrevorBivi** [comment]
Hello, thanks for your interest! I believe I had Python 3.5 installed when I was working on this project.
